// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDww3g5_7eb5o8175bl_32yEahKiSHW9o4',
    appId: '1:671082440332:web:8faf5c0a5450d8695e7da9',
    messagingSenderId: '671082440332',
    projectId: 'itiproject-e11db',
    authDomain: 'itiproject-e11db.firebaseapp.com',
    storageBucket: 'itiproject-e11db.appspot.com',
    measurementId: 'G-X7FX7RGKX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0FGcyEm34N_DsBjD4xALEXyZ889PYG0',
    appId: '1:671082440332:android:1779b13d657fa07b5e7da9',
    messagingSenderId: '671082440332',
    projectId: 'itiproject-e11db',
    storageBucket: 'itiproject-e11db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDPG3lJUs9cIbJ_CDPuV_mNpxeLOdxUGI',
    appId: '1:671082440332:ios:945a6096d4ad339d5e7da9',
    messagingSenderId: '671082440332',
    projectId: 'itiproject-e11db',
    storageBucket: 'itiproject-e11db.appspot.com',
    iosClientId: '671082440332-to5tvl835ese21qrirv0buq3pbju6ffk.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
